// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Mindfulness UI

#ifndef _MINDFULNESS_UI_UI_H
#define _MINDFULNESS_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

#include "ui_img_manager.h"
void image22scl_Animation(lv_obj_t * TargetObject, int delay);
void image23scl_Animation(lv_obj_t * TargetObject, int delay);
void image24scl_Animation(lv_obj_t * TargetObject, int delay);
void image25scl_Animation(lv_obj_t * TargetObject, int delay);
void image1scl_Animation(lv_obj_t * TargetObject, int delay);
void image14scl_Animation(lv_obj_t * TargetObject, int delay);
void image13scl_Animation(lv_obj_t * TargetObject, int delay);
void image12scl_Animation(lv_obj_t * TargetObject, int delay);
void image11scl_Animation(lv_obj_t * TargetObject, int delay);
void image10scl_Animation(lv_obj_t * TargetObject, int delay);
void image9scl_Animation(lv_obj_t * TargetObject, int delay);
void image8scl_Animation(lv_obj_t * TargetObject, int delay);
void image7scl_Animation(lv_obj_t * TargetObject, int delay);
void image6scl_Animation(lv_obj_t * TargetObject, int delay);
void image5scl_Animation(lv_obj_t * TargetObject, int delay);
void image4scl_Animation(lv_obj_t * TargetObject, int delay);
void image2scl_Animation(lv_obj_t * TargetObject, int delay);
void image32ops_Animation(lv_obj_t * TargetObject, int delay);
void image31op_Animation(lv_obj_t * TargetObject, int delay);
void image30op_Animation(lv_obj_t * TargetObject, int delay);
void image29op_Animation(lv_obj_t * TargetObject, int delay);
void image28op_Animation(lv_obj_t * TargetObject, int delay);
void image27op_Animation(lv_obj_t * TargetObject, int delay);
void image3op_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image32;
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_Image30;
extern lv_obj_t * ui_Image29;
extern lv_obj_t * ui_Image28;
extern lv_obj_t * ui_Image27;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Image20;
// CUSTOM VARIABLES

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
extern lv_image_dsc_t ui_img_group_14_png;   // assets/Group 14.png
void ui_img_group_14_png_load();
extern lv_image_dsc_t ui_img_group_13_png;   // assets/Group 13.png
void ui_img_group_13_png_load();
extern lv_image_dsc_t ui_img_group_12_png;   // assets/Group 12.png
void ui_img_group_12_png_load();
extern lv_image_dsc_t ui_img_group_11_png;   // assets/Group 11.png
void ui_img_group_11_png_load();
extern lv_image_dsc_t ui_img_group_10_png;   // assets/Group 10.png
void ui_img_group_10_png_load();
extern lv_image_dsc_t ui_img_group_9_png;   // assets/Group 9.png
void ui_img_group_9_png_load();
extern lv_image_dsc_t ui_img_group_8_png;   // assets/Group 8.png
void ui_img_group_8_png_load();
extern lv_image_dsc_t ui_img_group_7_png;   // assets/Group 7.png
void ui_img_group_7_png_load();
extern lv_image_dsc_t ui_img_group_6_png;   // assets/Group 6.png
void ui_img_group_6_png_load();
extern lv_image_dsc_t ui_img_group_5_png;   // assets/Group 5.png
void ui_img_group_5_png_load();
extern lv_image_dsc_t ui_img_group_4_png;   // assets/Group 4.png
void ui_img_group_4_png_load();
extern lv_image_dsc_t ui_img_group_27_png;   // assets/Group 27.png
void ui_img_group_27_png_load();
extern lv_image_dsc_t ui_img_group_26_png;   // assets/Group 26.png
void ui_img_group_26_png_load();
extern lv_image_dsc_t ui_img_group_25_png;   // assets/Group 25.png
void ui_img_group_25_png_load();
extern lv_image_dsc_t ui_img_group_24_png;   // assets/Group 24.png
void ui_img_group_24_png_load();
extern lv_image_dsc_t ui_img_group_23_png;   // assets/Group 23.png
void ui_img_group_23_png_load();
extern lv_image_dsc_t ui_img_group_22_png;   // assets/Group 22.png
void ui_img_group_22_png_load();
extern lv_image_dsc_t ui_img_group_3_png;   // assets/Group 3.png
void ui_img_group_3_png_load();
extern lv_image_dsc_t ui_img_group_2_png;   // assets/Group 2.png
void ui_img_group_2_png_load();
extern lv_image_dsc_t ui_img_group_1_png;   // assets/Group 1.png
void ui_img_group_1_png_load();
extern lv_image_dsc_t ui_img_group_16_png;   // assets/Group 16.png
void ui_img_group_16_png_load();
extern lv_image_dsc_t ui_img_group_17_png;   // assets/Group 17.png
void ui_img_group_17_png_load();
extern lv_image_dsc_t ui_img_group_18_png;   // assets/Group 18.png
void ui_img_group_18_png_load();
extern lv_image_dsc_t ui_img_group_19_png;   // assets/Group 19.png
void ui_img_group_19_png_load();
extern lv_image_dsc_t ui_img_group_20_png;   // assets/Group 20.png
void ui_img_group_20_png_load();
extern lv_image_dsc_t ui_img_group_15_png;   // assets/Group 15.png
void ui_img_group_15_png_load();

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
