// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Mindfulness UI

#include "ui.h"


// IMAGE DATA: assets/Group 26.png
lv_image_dsc_t ui_img_group_26_png = {
    .header.w = 339,
    .header.h = 339,
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .header.magic = LV_IMAGE_HEADER_MAGIC,
};

void ui_img_group_26_png_load()
{
    ui_img_group_26_png.data = UI_LOAD_IMAGE("S:/ui_img_group_26_png.bin", 2925, 344763);
    ui_img_group_26_png.data_size = 344763;
}
