// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Mindfulness UI

#include "ui.h"


// IMAGE DATA: assets/Group 18.png
lv_image_dsc_t ui_img_group_18_png = {
    .header.w = 200,
    .header.h = 200,
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .header.magic = LV_IMAGE_HEADER_MAGIC,
};

void ui_img_group_18_png_load()
{
    ui_img_group_18_png.data = UI_LOAD_IMAGE("S:/ui_img_group_18_png.bin", 1510, 120000);
    ui_img_group_18_png.data_size = 120000;
}
