// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Mindfulness UI

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image14, &ui_img_group_14_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image13, &ui_img_group_13_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image12, &ui_img_group_12_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image11, &ui_img_group_11_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image10, &ui_img_group_10_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image9, &ui_img_group_9_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image8, &ui_img_group_8_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image7, &ui_img_group_7_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image6, &ui_img_group_6_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image5, &ui_img_group_5_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image4, &ui_img_group_4_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image32 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image32, &ui_img_group_27_png);
    lv_obj_set_width(ui_Image32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image32, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image32, -2280);

    ui_Image31 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image31, &ui_img_group_26_png);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image31, -1800);

    ui_Image30 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image30, &ui_img_group_25_png);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image30, -1320);

    ui_Image29 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image29, &ui_img_group_24_png);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image29, -830);

    ui_Image28 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image28, &ui_img_group_23_png);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image28, -360);

    ui_Image27 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image27, &ui_img_group_22_png);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image27, 110);

    ui_Image3 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image3, &ui_img_group_3_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image2, &ui_img_group_2_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image1, &ui_img_group_1_png);
    lv_obj_set_width(ui_Image1, 240);
    lv_obj_set_height(ui_Image1, 240);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image21 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image21, &ui_img_group_16_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image22 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image22, &ui_img_group_17_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image23 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image23, &ui_img_group_18_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image24 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image24, &ui_img_group_19_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image25 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image25, &ui_img_group_20_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image20, &ui_img_group_15_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
